/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.io.IOException;
import java.io.InputStreamReader;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Properties;

import javax.swing.JOptionPane;
import modelo.Persistencia;
import modelo.PersistenciaHibernate;
import modelo.PersistenciaJDBC;
import controlador.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author alumno
 */
public class Clientes extends javax.swing.JDialog {

    static String cod;
    Persistencia p;

    /**
     * Creates new form Clientes
     */
    public Clientes(java.awt.Frame parent, boolean modal, String cod) {
        super(parent, modal);
        this.cod = cod;

        try {
            conectar();
        } catch (IOException ex) {

            JOptionPane.showMessageDialog(null, ex.getMessage());

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Comprueba los parametros de acceso.\n" + ex.getMessage(),
                    "ERROR FATAL", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }

        initComponents();
        jLabelError.setVisible(false);
        jLabelCabe.setVisible(false);
        setLocationRelativeTo(null);
        jPanel1.setVisible(false);

        if (cod != null) {

            jTextFieldCod.setEnabled(false);
            jButtonAcep.setEnabled(false);
            jPanel1.setVisible(true);
            jTextFieldNombre.grabFocus();
            jLabelCabe.setText("Añadir Cliente: ");
            jLabelCabe.setVisible(true);

        }

    }

    private void conectar() throws SQLException, IOException {

        Properties prop = new Properties();
        prop.load(new InputStreamReader(PersistenciaJDBC.class.getResourceAsStream("CFG.INI")));
        String s = prop.getProperty("tipoPersistencia").toLowerCase();

        switch (s) {

            case "mysqljdbc":
                p = new PersistenciaJDBC();
                break;

            case "hibernate":
                p = new PersistenciaHibernate();
                break;

            default:
                JOptionPane.showMessageDialog(this, "El tipo de persistencia no es válido (mysqlJDBC o Hibernate)",
                        "FATAL ERROR", JOptionPane.ERROR_MESSAGE);
                System.exit(0);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jTextFieldCod = new javax.swing.JTextField();
		jButtonAcep = new javax.swing.JButton();
		jPanel1 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jTextFieldNombre = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jTextFieldApe = new javax.swing.JTextField();
		jTextFieldApe2 = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jTextFieldDir = new javax.swing.JTextField();
		jButtonCan = new javax.swing.JButton();
		jButtonGrab = new javax.swing.JButton();
		jLabelError = new javax.swing.JLabel();
		jLabelCabe = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setResizable(false);

		jLabel1.setText("Código: ");

		jTextFieldCod.setText(cod);
		jTextFieldCod.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextFieldCodActionPerformed(evt);
			}
		});

		jButtonAcep.setText("Aceptar");
		jButtonAcep.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonAcepActionPerformed(evt);
			}
		});

		jLabel2.setText("Nombre: ");

		jLabel3.setText("Apellidos: ");

		jLabel4.setText("Dirección:");

		jButtonCan.setText("Cancelar");
		jButtonCan.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonCanActionPerformed(evt);
			}
		});

		jButtonGrab.setText("Guardar");
		jButtonGrab.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonGrabActionPerformed(evt);
			}
		});

		jLabelError.setForeground(new java.awt.Color(255, 0, 0));
		jLabelError.setText("* Rellene todos los campos");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(24, 24, 24)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
								.addGroup(javax.swing.GroupLayout.Alignment.LEADING,
										jPanel1Layout.createSequentialGroup()
												.addComponent(jLabelError, javax.swing.GroupLayout.PREFERRED_SIZE, 203,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jButtonGrab)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jButtonCan))
								.addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.LEADING,
										jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel3).addComponent(jLabel2)
												.addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE,
														150, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jTextFieldApe)).addGap(18, 18, 18)
												.addComponent(jTextFieldApe2, javax.swing.GroupLayout.PREFERRED_SIZE,
														190, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addComponent(jTextFieldDir, javax.swing.GroupLayout.Alignment.LEADING))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(jLabel2)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel3)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jTextFieldApe, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jTextFieldApe2, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel4)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jTextFieldDir, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jButtonCan).addComponent(jLabelError).addComponent(jButtonGrab))
						.addContainerGap(25, Short.MAX_VALUE)));

		jLabelCabe.setText("Modificar Cliente: ");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addGroup(layout.createSequentialGroup().addGap(24, 24, 24)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabelCabe).addComponent(jLabel1)
								.addGroup(layout.createSequentialGroup()
										.addComponent(jTextFieldCod, javax.swing.GroupLayout.PREFERRED_SIZE, 150,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18).addComponent(jButtonAcep)))
						.addContainerGap(168, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jLabelCabe)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel1)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jTextFieldCod, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jButtonAcep))
						.addGap(18, 18, 18).addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

    private void jButtonAcepActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonAcepActionPerformed
        // TODO add your handling code here:

        if (jTextFieldCod.getText().matches("[0-9]{1,6}")) {

            try {

                ArrayList<Cliente> cli = p.consultarCli(Integer.parseInt(jTextFieldCod.getText()));

                if (!cli.isEmpty()) {

                    jTextFieldNombre.setText(cli.get(0).getNombre());
                    jTextFieldApe.setText(cli.get(0).getApe1());
                    jTextFieldApe2.setText(cli.get(0).getApe2());
                    jTextFieldDir.setText(cli.get(0).getDireccion());
                    jPanel1.setVisible(true);
                    jLabelCabe.setText("Modificar Cliente: ");
                    jLabelCabe.setVisible(true);

                } else {

                    int i = Integer.parseInt(jTextFieldCod.getText());
                    jPanel1.setVisible(true);
                    jLabelCabe.setText("Añadir Cliente: ");
                    jLabelCabe.setVisible(true);

                }

                jTextFieldCod.setEnabled(false);
                jButtonAcep.setEnabled(false);

            } catch (SQLException ex) {

                JOptionPane.showMessageDialog(this, ex.getMessage());

            }

        } else {

            JOptionPane.showMessageDialog(this, "El código debe ser un dígito de máximo 6 dígitos",
                    "ERROR", JOptionPane.ERROR_MESSAGE);

            jTextFieldCod.setText(null);
            jTextFieldCod.grabFocus();

        }

    }// GEN-LAST:event_jButtonAcepActionPerformed

    private void jButtonGrabActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonGrabActionPerformed
        // TODO add your handling code here:

        if (camposValidos()) {

            Cliente c = new Cliente(Integer.parseInt(jTextFieldCod.getText()), jTextFieldNombre.getText(),
                    jTextFieldApe.getText(), jTextFieldApe2.getText(), jTextFieldDir.getText());

            try {
                p.guardarModCli(c);
            } catch (SQLException ex) {

                JOptionPane.showMessageDialog(this, ex.getMessage());
            }

            this.dispose();
        }

    }// GEN-LAST:event_jButtonGrabActionPerformed

    private void jTextFieldCodActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldCodActionPerformed
        // TODO add your handling code here:

        jButtonAcepActionPerformed(evt);

    }// GEN-LAST:event_jTextFieldCodActionPerformed

    private void jButtonCanActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonCanActionPerformed
        // TODO add your handling code here:

        jTextFieldCod.setEnabled(true);
        jTextFieldCod.setText(null);
        jTextFieldCod.grabFocus();
        jButtonAcep.setEnabled(true);
        jTextFieldNombre.setText(null);
        jTextFieldApe.setText(null);
        jTextFieldApe2.setText(null);
        jTextFieldDir.setText(null);
        jPanel1.setVisible(false);
        jLabelCabe.setVisible(false);
        jLabelCabe.setText("Modificar Cliente: ");
        jLabelError.setVisible(false);

    }// GEN-LAST:event_jButtonCanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Clientes dialog = new Clientes(new javax.swing.JFrame(), true, cod);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButtonAcep;
	private javax.swing.JButton jButtonCan;
	private javax.swing.JButton jButtonGrab;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabelCabe;
	private javax.swing.JLabel jLabelError;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JTextField jTextFieldApe;
	private javax.swing.JTextField jTextFieldApe2;
	private javax.swing.JTextField jTextFieldCod;
	private javax.swing.JTextField jTextFieldDir;
	private javax.swing.JTextField jTextFieldNombre;
	// End of variables declaration//GEN-END:variables

    private boolean camposValidos() {

        boolean val = true;

        if (!jTextFieldNombre.getText().equals("")) {
            if (!jTextFieldApe.getText().equals("")) {
                if (!jTextFieldApe2.getText().equals("")) {
                    if (!jTextFieldDir.getText().equals("")) {

                    } else {

                        jTextFieldDir.grabFocus();
                        jLabelError.setVisible(true);
                        val = false;

                    }
                } else {

                    jTextFieldApe2.grabFocus();
                    jLabelError.setVisible(true);
                    val = false;
                }
            } else {

                jTextFieldApe.grabFocus();
                jLabelError.setVisible(true);
                val = false;
            }
        } else {

            jTextFieldNombre.grabFocus();
            jLabelError.setVisible(true);
            val = false;
        }

        return val;
    }
}
