/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.io.IOException;
import java.io.InputStreamReader;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelo.Persistencia;
import modelo.PersistenciaHibernate;
import modelo.PersistenciaJDBC;
import controlador.*;
import java.util.Vector;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author sortKrage
 */
public class Empleados extends javax.swing.JDialog {

    Persistencia p;

    /**
     * Creates new form Empleados
     */
    public Empleados(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try {
            conectar();
        } catch (IOException ex) {

            JOptionPane.showMessageDialog(null, ex.getMessage());

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Comprueba los parametros de acceso\n" + ex.getMessage(),
                    "ERROR FATAL", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }

        try {

            Vector data = p.cargarPuesto();

            if (data.isEmpty()) {

                JOptionPane.showMessageDialog(this, "No existen puestos disponibles", "ERROR",
                        JOptionPane.ERROR_MESSAGE);
                this.dispose();

            } else {

                initComponents();
                setLocationRelativeTo(null);
                jPanel1.setVisible(false);
                jLabel4.setVisible(false);
                jLabel5.setVisible(false);
                ComboBoxModel cbm = new DefaultComboBoxModel(data);
                jComboBoxPuesto.setModel(cbm);
            }

        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(null, ex.getMessage());

        }

    }

    private void conectar() throws SQLException, IOException {

        Properties prop = new Properties();
        prop.load(new InputStreamReader(PersistenciaJDBC.class.getResourceAsStream("CFG.INI")));
        String s = prop.getProperty("tipoPersistencia").toLowerCase();

        switch (s) {

            case "mysqljdbc":
                p = new PersistenciaJDBC();
                break;

            case "hibernate":
                p = new PersistenciaHibernate();
                break;

            default:
                JOptionPane.showMessageDialog(this, "El tipo de persistencia no es válido (mysqlJDBC o Hibernate)",
                        "FATAL ERROR", JOptionPane.ERROR_MESSAGE);
                System.exit(0);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jTextFieldCod = new javax.swing.JTextField();
		jButtonAcep = new javax.swing.JButton();
		jPanel1 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jTextFieldNom = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jTextFieldApe2 = new javax.swing.JTextField();
		jTextFieldApe = new javax.swing.JTextField();
		jComboBoxPuesto = new javax.swing.JComboBox();
		jButtonGuardar = new javax.swing.JButton();
		jButtonCan = new javax.swing.JButton();
		jLabel5 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setResizable(false);

		jLabel1.setText("Código: ");

		jTextFieldCod.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextFieldCodActionPerformed(evt);
			}
		});

		jButtonAcep.setText("Aceptar");
		jButtonAcep.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonAcepActionPerformed(evt);
			}
		});

		jLabel2.setText("Nombre");

		jLabel3.setText("Apellidos");

		jTextFieldApe2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextFieldApe2ActionPerformed(evt);
			}
		});

		jComboBoxPuesto.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "Gerente", "Encargado", "Repartidor", "Cocinero", "Cajero" }));

		jButtonGuardar.setText("Guardar");
		jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonGuardarActionPerformed(evt);
			}
		});

		jButtonCan.setText("Cancelar");
		jButtonCan.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonCanActionPerformed(evt);
			}
		});

		jLabel5.setForeground(new java.awt.Color(255, 0, 0));
		jLabel5.setText("* Rellene todos los campos");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(24, 24, 24)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup().addComponent(jLabel5).addGap(18, 18, 18)
										.addComponent(jButtonGuardar)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButtonCan))
								.addGroup(jPanel1Layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
										.addGroup(javax.swing.GroupLayout.Alignment.LEADING,
												jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addGroup(jPanel1Layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.TRAILING,
																		false)
																.addComponent(jLabel3,
																		javax.swing.GroupLayout.Alignment.LEADING,
																		javax.swing.GroupLayout.DEFAULT_SIZE, 150,
																		Short.MAX_VALUE)
																.addComponent(jLabel2,
																		javax.swing.GroupLayout.Alignment.LEADING,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE))
														.addComponent(jTextFieldApe,
																javax.swing.GroupLayout.DEFAULT_SIZE, 180,
																Short.MAX_VALUE)
														.addComponent(jTextFieldNom)).addGap(18, 18, 18)
														.addComponent(jTextFieldApe2))
										.addComponent(jComboBoxPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 383,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(23, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(jLabel2)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel3)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jTextFieldApe, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jTextFieldApe2, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addComponent(jComboBoxPuesto, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jButtonGuardar).addComponent(jButtonCan).addComponent(jLabel5))
						.addContainerGap(23, Short.MAX_VALUE)));

		jLabel4.setText("Crear Empleado:");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addGroup(layout.createSequentialGroup().addGap(24, 24, 24)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel4)
								.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 318,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(layout.createSequentialGroup()
										.addComponent(jTextFieldCod, javax.swing.GroupLayout.PREFERRED_SIZE, 150,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18).addComponent(jButtonAcep)))
						.addContainerGap(100, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jLabel4)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel1)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jTextFieldCod, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jButtonAcep))
						.addGap(18, 18, 18).addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCodActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldCodActionPerformed
        // TODO add your handling code here:

        jButtonAcepActionPerformed(evt);

    }// GEN-LAST:event_jTextFieldCodActionPerformed

    private void jButtonAcepActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonAcepActionPerformed
        // TODO add your handling code here:

        String cod = jTextFieldCod.getText();

        if (jTextFieldCod.getText().matches("[0-9]{1,6}")) {

            try {
                ArrayList<Empleado> emp = p.consultarEmp(cod);

                if (!emp.isEmpty()) {

                    jLabel4.setText("Modificar empleado: ");
                    jLabel4.setVisible(true);

                    jTextFieldCod.setEnabled(false);
                    jButtonAcep.setEnabled(false);

                    jTextFieldNom.setText(emp.get(0).getNombre());
                    jTextFieldApe.setText(emp.get(0).getApe1());
                    jTextFieldApe2.setText(emp.get(0).getApe2());
                    jComboBoxPuesto.setSelectedIndex(emp.get(0).getPuesto().getIdPuesto() - 1);

                } else {

                    jLabel4.setText("Crear empleado: ");
                    jLabel4.setVisible(true);

                }

                jPanel1.setVisible(true);

            } catch (SQLException ex) {
            }
        } else {

            JOptionPane.showMessageDialog(this, "El código debe ser un número de máximo 6 dígitos", "ERROR",
                    JOptionPane.ERROR_MESSAGE);

            jTextFieldCod.setText(null);
            jTextFieldCod.grabFocus();

        }

    }// GEN-LAST:event_jButtonAcepActionPerformed

    private void jTextFieldApe2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldApe2ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextFieldApe2ActionPerformed

    private void jButtonCanActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonCanActionPerformed
        // TODO add your handling code here:

        jTextFieldCod.setText(null);
        jTextFieldCod.grabFocus();
        jTextFieldNom.setText(null);
        jTextFieldApe.setText(null);
        jTextFieldApe2.setText(null);
        jTextFieldCod.setEnabled(true);
        jButtonAcep.setEnabled(true);
        jLabel4.setVisible(false);
        jPanel1.setVisible(false);

    }// GEN-LAST:event_jButtonCanActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:

        if (validarCampos()) {

            Empleado emp = new Empleado(Integer.parseInt(jTextFieldCod.getText()),
                    new Puesto(jComboBoxPuesto.getSelectedIndex() + 1), jTextFieldNom.getText(), jTextFieldApe.getText(),
                    jTextFieldApe2.getText(), 0);

            try {
                p.guardarModEmp(emp);
            } catch (SQLException ex) {
                Logger.getLogger(Empleados.class.getName()).log(Level.SEVERE, null, ex);
            }

            jButtonCanActionPerformed(evt);

        }

    }// GEN-LAST:event_jButtonGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Empleados dialog = new Empleados(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButtonAcep;
	private javax.swing.JButton jButtonCan;
	private javax.swing.JButton jButtonGuardar;
	private javax.swing.JComboBox jComboBoxPuesto;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JTextField jTextFieldApe;
	private javax.swing.JTextField jTextFieldApe2;
	private javax.swing.JTextField jTextFieldCod;
	private javax.swing.JTextField jTextFieldNom;
	// End of variables declaration//GEN-END:variables

    private boolean validarCampos() {
        boolean val = true;

        if (!jTextFieldNom.getText().equals("")) {
            if (!jTextFieldApe.getText().equals("")) {
                if (!jTextFieldApe2.getText().equals("")) {

                } else {

                    jLabel5.setVisible(true);
                    jTextFieldApe2.setText(null);
                    jTextFieldApe2.grabFocus();

                    val = false;

                }
            } else {

                jLabel5.setVisible(true);
                jTextFieldApe.setText(null);
                jTextFieldApe.grabFocus();

                val = false;

            }

        } else {

            jLabel5.setVisible(true);
            jTextFieldNom.setText(null);
            jTextFieldNom.grabFocus();

            val = false;

        }

        return val;
    }
}
