/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.io.IOException;
import java.io.InputStreamReader;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Enumeration;
import java.util.Properties;
import java.util.Vector;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Persistencia;
import modelo.PersistenciaHibernate;
import modelo.PersistenciaJDBC;

/**
 *
 * @author alumno
 */
public class Ventas extends javax.swing.JDialog {

    Persistencia p;

    /**
     * Creates new form Ventas
     */
    public Ventas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        try {
            conectar();
        } catch (IOException ex) {

            JOptionPane.showMessageDialog(null, ex.getMessage());

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Comprueba los parametros de acceso\n" + ex.getMessage(),
                    "ERROR FATAL", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }

        initComponents();
        setLocationRelativeTo(null);
        jTextFieldTotal.setEditable(false);
        dateChooserCombo.setDateFormat(new SimpleDateFormat("yyyy-MM-dd"));
        dateChooserCombo2.setDateFormat(new SimpleDateFormat("yyyy-MM-dd"));

    }

    private void conectar() throws SQLException, IOException {

        Properties prop = new Properties();
        prop.load(new InputStreamReader(PersistenciaJDBC.class.getResourceAsStream("CFG.INI")));
        String s = prop.getProperty("tipoPersistencia").toLowerCase();

        switch (s) {

            case "mysqljdbc":
                p = new PersistenciaJDBC();
                break;

            case "hibernate":
                p = new PersistenciaHibernate();
                break;

            default:
                JOptionPane.showMessageDialog(this, "El tipo de persistencia no es válido (mysqlJDBC o Hibernate)",
                        "FATAL ERROR", JOptionPane.ERROR_MESSAGE);
                System.exit(0);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButtonFecha = new javax.swing.JRadioButton();
        jRadioButtonCliente = new javax.swing.JRadioButton();
        jRadioButtonEmp = new javax.swing.JRadioButton();
        dateChooserCombo = new datechooser.beans.DateChooserCombo();
        dateChooserCombo2 = new datechooser.beans.DateChooserCombo();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldCod = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldTotal = new javax.swing.JTextField();
        jButtonAcep = new javax.swing.JButton();
        jButtonOtra = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        buttonGroup1.add(jRadioButtonFecha);
        jRadioButtonFecha.setSelected(true);
        jRadioButtonFecha.setText("Fecha");
        jRadioButtonFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFechaActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonCliente);
        jRadioButtonCliente.setText("Cliente");
        jRadioButtonCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonClienteActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonEmp);
        jRadioButtonEmp.setText("Empleado");
        jRadioButtonEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEmpActionPerformed(evt);
            }
        });

        dateChooserCombo.setCalendarPreferredSize(new java.awt.Dimension(375, 305));
        dateChooserCombo.setNothingAllowed(false);
        dateChooserCombo.setBehavior(datechooser.model.multiple.MultyModelBehavior.SELECT_SINGLE);

        dateChooserCombo2.setCalendarPreferredSize(new java.awt.Dimension(375, 305));
        dateChooserCombo2.setCurrentNavigateIndex(0);
        dateChooserCombo2.setBehavior(datechooser.model.multiple.MultyModelBehavior.SELECT_SINGLE);

        jLabel1.setText("Código: ");

        jTextFieldCod.setEnabled(false);
        jTextFieldCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("TOTAL: ");

        jButtonAcep.setText("Aceptar");
        jButtonAcep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcepActionPerformed(evt);
            }
        });

        jButtonOtra.setText("Otra consulta");
        jButtonOtra.setEnabled(false);
        jButtonOtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOtraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonOtra))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jRadioButtonFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jRadioButtonCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jRadioButtonEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dateChooserCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(dateChooserCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldCod, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonAcep, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1))
                .addGap(0, 24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButtonFecha)
                    .addComponent(dateChooserCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateChooserCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonCliente)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonEmp))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAcep))))
                .addGap(18, 20, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonOtra))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodActionPerformed
        // TODO add your handling code here:

        jButtonAcepActionPerformed(evt);

    }//GEN-LAST:event_jTextFieldCodActionPerformed

    private void jRadioButtonClienteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioButtonClienteActionPerformed
        // TODO add your handling code here:

        dateChooserCombo2.setEnabled(false);
        dateChooserCombo.setEnabled(false);
        jTextFieldCod.setEnabled(true);
        jTextFieldCod.setText(null);

    }// GEN-LAST:event_jRadioButtonClienteActionPerformed

    private void jRadioButtonEmpActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioButtonEmpActionPerformed
        // TODO add your handling code here:
        jRadioButtonClienteActionPerformed(evt);
    }// GEN-LAST:event_jRadioButtonEmpActionPerformed

    private void jRadioButtonFechaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioButtonFechaActionPerformed
        // TODO add your handling code here:

        dateChooserCombo2.setEnabled(true);
        dateChooserCombo.setEnabled(true);
        jTextFieldCod.setEnabled(false);
        jTextFieldCod.setText(null);

    }// GEN-LAST:event_jRadioButtonFechaActionPerformed

    private void jButtonAcepActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonAcepActionPerformed
        // TODO add your handling code here:

        Vector resul = new Vector();
        Vector titColumn = new Vector();
        titColumn.addElement("Código");
        titColumn.addElement("Importe");

        try {

            switch (getSelectedButton()) {

                case 0:

                    resul = p.estadisticaPorFecha(dateChooserCombo.getText(), dateChooserCombo2.getText());

                    break;
                case 1:

                    if (!jTextFieldCod.getText().matches("[0-9]{1,6}")) {

                        JOptionPane.showMessageDialog(this, "El código debe ser un número de máximo 6 digitos",
                                "ERROR", JOptionPane.ERROR_MESSAGE);

                    } else {

                        resul = p.estadisticaPorCod("Cliente", jTextFieldCod.getText());

                    }
                    break;
                case 2:

                    if (!jTextFieldCod.getText().matches("[0-9]{1,6}")) {

                        JOptionPane.showMessageDialog(this, "El código debe ser un número de máximo 6 digitos",
                                "ERROR", JOptionPane.ERROR_MESSAGE);

                    } else {

                        resul = p.estadisticaPorCod("Empleado", jTextFieldCod.getText());

                    }
                    break;

            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this, e.getMessage());

        }

        if (resul.isEmpty()) {

            JOptionPane.showMessageDialog(this, "No se ha encontrado coincidencias", "Resultados",
                    JOptionPane.INFORMATION_MESSAGE);
            jTextFieldCod.setText(null);

        } else {

            DefaultTableModel dtm = new DefaultTableModel(resul, titColumn) {

                @Override
                public boolean isCellEditable(int row, int column) {

                    return false;
                }

            };

            jTable1.setModel(dtm);
            jTextFieldCod.setEnabled(false);
            dateChooserCombo.setEnabled(false);
            dateChooserCombo2.setEnabled(false);
            jButtonAcep.setEnabled(false);
            jButtonOtra.setEnabled(true);
            jRadioButtonCliente.setEnabled(false);
            jRadioButtonEmp.setEnabled(false);
            jRadioButtonFecha.setEnabled(false);

            actualizarTotal();

        }

    }// GEN-LAST:event_jButtonAcepActionPerformed

    private void actualizarTotal() {

        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();

        double total = 0;

        for (int i = 0; i < dtm.getRowCount(); i++) {

            double nuevo = Double.parseDouble(String.valueOf(dtm.getValueAt(i, 1)));

            total = total + nuevo;

        }

        jTextFieldTotal.setText(String.valueOf(total));

    }

    private void jButtonOtraActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonOtraActionPerformed
        // TODO add your handling code here:

        dateChooserCombo.setEnabled(true);
        dateChooserCombo2.setEnabled(true);
        jButtonAcep.setEnabled(true);
        jTextFieldCod.setText(null);
        jRadioButtonFecha.setSelected(true);
        jTable1.setModel(new DefaultTableModel());
        jButtonOtra.setEnabled(false);
        jRadioButtonCliente.setEnabled(true);
        jRadioButtonEmp.setEnabled(true);
        jRadioButtonFecha.setEnabled(true);
        jTextFieldTotal.setText(null);

    }// GEN-LAST:event_jButtonOtraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Ventas dialog = new Ventas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private datechooser.beans.DateChooserCombo dateChooserCombo;
    private datechooser.beans.DateChooserCombo dateChooserCombo2;
    private javax.swing.JButton jButtonAcep;
    private javax.swing.JButton jButtonOtra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButtonCliente;
    private javax.swing.JRadioButton jRadioButtonEmp;
    private javax.swing.JRadioButton jRadioButtonFecha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldCod;
    private javax.swing.JTextField jTextFieldTotal;
    // End of variables declaration//GEN-END:variables

    private int getSelectedButton() {

        Enumeration<AbstractButton> consulta;

        int i = 0, selec = 0;

        for (consulta = buttonGroup1.getElements(); consulta.hasMoreElements();) {

            if (consulta.nextElement().isSelected()) {

                selec = i;

            }
            i++;
        }

        return selec;
    }
}
