package controlador;
// Generated 05-feb-2019 13:05:42 by Hibernate Tools 4.0.1.Final

import java.sql.Date;

/**
 * Pedido generated by hbm2java
 */
public class Pedido implements java.io.Serializable {

    private int idPedido;
    private int cliente;
    private int empleado;
    private Date fecha;
    private double importe;


    public Pedido() {
    }

    public Pedido(int idPedido) {
        this.idPedido = idPedido;
    }

    public Pedido(int cliente, int empleado, Date fecha, double importe) {
        this.cliente = cliente;
        this.empleado = empleado;
        this.fecha = fecha;
        this.importe = importe;
    }

    public int getIdPedido() {
        return this.idPedido;
    }

    public void setIdPedido(int idPedido) {
        this.idPedido = idPedido;
    }

    public int getCliente() {
        return this.cliente;
    }

    public void setCliente(int cliente) {
        this.cliente = cliente;
    }

    public int getEmpleado() {
        return this.empleado;
    }

    public void setEmpleado(int empleado) {
        this.empleado = empleado;
    }

    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public double getImporte() {
        return this.importe;
    }

    public void setImporte(double importe) {
        this.importe = importe;
    }

}
