package controlador;
// Generated 05-feb-2019 13:05:42 by Hibernate Tools 4.0.1.Final

/**
 * Puesto generated by hbm2java
 */
public class Puesto implements java.io.Serializable {

	private int idPuesto;
	private String nombre;
	private String descripcion;
	private Integer salarioHora;

	public Puesto() {
	}

	public Puesto(int idPuesto) {
		this.idPuesto = idPuesto;
	}

	public Puesto(int idPuesto, String nombre, String descripcion, Integer salarioHora) {
		this.idPuesto = idPuesto;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.salarioHora = salarioHora;
	}

	public int getIdPuesto() {
		return this.idPuesto;
	}

	public void setIdPuesto(int idPuesto) {
		this.idPuesto = idPuesto;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Integer getSalarioHora() {
		return this.salarioHora;
	}

	public void setSalarioHora(Integer salarioHora) {
		this.salarioHora = salarioHora;
	}

}
