package controlador;
// Generated 05-feb-2019 13:05:42 by Hibernate Tools 4.0.1.Final

/**
 * Venta generated by hbm2java
 */
public class Venta implements java.io.Serializable {

	private Integer idPedido;
	private Integer idArticulo;
	private Integer cantidad;

	public Venta() {
	}

	public Venta(Integer idPedido, Integer idArticulo, Integer cantidad) {
		this.idPedido = idPedido;
		this.idArticulo = idArticulo;
		this.cantidad = cantidad;
	}

	public Integer getIdPedido() {
		return this.idPedido;
	}

	public void setIdPedido(Integer idPedido) {
		this.idPedido = idPedido;
	}

	public Integer getIdArticulo() {
		return this.idArticulo;
	}

	public void setIdArticulo(Integer idArticulo) {
		this.idArticulo = idArticulo;
	}

	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Venta))
			return false;
		Venta castOther = (Venta) other;

		return ((this.getIdPedido() == castOther.getIdPedido()) || (this.getIdPedido() != null
				&& castOther.getIdPedido() != null && this.getIdPedido().equals(castOther.getIdPedido())))
				&& ((this.getIdArticulo() == castOther.getIdArticulo()) || (this.getIdArticulo() != null
						&& castOther.getIdArticulo() != null && this.getIdArticulo().equals(castOther.getIdArticulo())))
				&& ((this.getCantidad() == castOther.getCantidad()) || (this.getCantidad() != null
						&& castOther.getCantidad() != null && this.getCantidad().equals(castOther.getCantidad())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdPedido() == null ? 0 : this.getIdPedido().hashCode());
		result = 37 * result + (getIdArticulo() == null ? 0 : this.getIdArticulo().hashCode());
		result = 37 * result + (getCantidad() == null ? 0 : this.getCantidad().hashCode());
		return result;
	}

}
